[package]
name = "blag"
version = "0.1.0"
authors = ["Nick Pillitteri <nick@tshlabs.org>"]
edition = "2018"

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper.git", features = ["runtime", "unstable-stream"] }
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
tokio = "0.2.0-alpha.6"
trust-dns-rustls = "0.7.0"
