[package]
name = "donut"
version = "0.1.0"
authors = ["Nick Pillitteri <nick@tshlabs.org>"]
edition = "2018"

[dependencies]
base64 = "0.11.0"
clap = "2.33"
failure = "0.1.6"
hyper = { git = "https://github.com/hyperium/hyper.git", features = ["runtime", "unstable-stream"] }
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
tokio = "0.2.0-alpha.6"
trust-dns = "0.17.0"
url = "2.1.0"

[lib]
name = "donut"
path = "src/donut/lib.rs"
