[package]
name = "blag"
version = "0.1.0"
authors = ["Nick Pillitteri <nick@tshlabs.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha.6"
futures-util-preview = "0.3.0-alpha.19"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
features = ["runtime", "unstable-stream"]