version: 2.1
orbs:
  rust: glotrade/rust@0.1.3

workflows:
  workflow:
    jobs:
      - rust/clippy:
          toolchain: "stable"
      - rust/format:
          toolchain: "stable"
      - rust/test:
          toolchain: "stable"
